Rename file for Windows compatibility
The repository can't be cloned on Windows because of invalid path:

    error: invalid path 'screenshot1200*800.png'